#项目配置
properties:
  gateway:
    sessionHeaderKey: x-tif-sessionid
    userHeaderKey: x-tif-uid
  wx:
    appid: wx1b023cc14a212804
    secret: 9c8b4949ba1ad1c8af474431f54cdff7
server:
  port: 8080
spring:
  redis:
    database: 0
    host: 192.168.13.39
    port: 6379
    password: a