#项目配置
properties:
  gateway:
    session-header-key: x-tif-sessionid
    user-header-key: x-tif-uid
  wx:
    appid: wx1b023cc14a212804
    secret: 9c8b4949ba1ad1c8af474431f54cdff7
  validate-face:
    appid: 4818
    secret-key: 5dffe557603cdc4079b6a33554760837
    result-key: a98fe02e5d0075fc2089a3c3cb21f260
    expired: 600
server:
  port: 8081
spring:
  redis:
    database: 0
    host: 192.168.13.39
    port: 6379
    password: a