#项目配置
properties:
  wx:
    appid: wx1b023cc14a212804
    secret: 9c8b4949ba1ad1c8af474431f54cdff7
  validate-face:
    tokenExpired: 60 #人脸识别token过期时间，单位分钟
    appid: 4818
    secret-key: 5dffe557603cdc4079b6a33554760837
    result-key: a98fe02e5d0075fc2089a3c3cb21f260
    signatureExpired: 600 #人脸识别拉取签名有效期，单位秒
    ftp-upload:
      delayTime: 3600000
      saveNumberOnce: 10
      stopSaveTime: 7
      machineId: 1
      username: lfq
      password: lfq
      hostname: 192.168.51.45
      port: 21
      path_ftp: /data/
      imgPath_suf_jpg: .jpg
      videoPath_suf: .mp4
server:
  port: 8081
spring:
  redis:
    database: 0
    host: 192.168.13.39
    port: 6379
    password: a
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.14.12:1521:ora10g
    username: minipro_dg_jccs
    password: a
mybatis:
  mapper-locations: classpath:mybatis/mapper/**/*Mapper.xml
  config-location: classpath:mybatis/mybatis-config.xml
logging:
  level:
     cn.hnisi: debug